### ISSUE TITLE
Magic is not working

### ISSUE THREAD

**Issue by LinkDragmire** [ortegamarcel/fvtt-token-action-hud-thewitchertrpg#12]
Available spells are not listed in the HUD

**Comment by ortegamarcel** [comment]
Which version of the system are you using? Can you press f12 to open the console, refresh the game with f5 and then see if there show up any error messages. And send them to me.

**Comment by LinkDragmire** [comment]
This is the error, when trying to open the magic tab:

Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'current')
[Detected 2 packages: fvtt-token-action-hud-thewitchertrpg, token-action-hud-core]
    at action-handler.js:169:76
    at Array.map (<anonymous>)
    at ActionHandler._getProfessionSkills (action-handler.js:159:18)
    at ActionHandler.buildSystemActions (action-handler.js:44:18)
    at ActionHandler._buildSystemActions (token-action-hud-core.min.js:1:29989)
    at ActionHandler.buildHud (token-action-hud-core.min.js:1:28043)
    at async TokenActionHud._updateHud (token-action-hud-core.min.js:1:74682)

**Comment by LinkDragmire** [comment]
![image](https://user-images.githubusercontent.com/125952214/236821506-784ed252-a926-4456-babe-8ba8aa142b50.png)
Using this version, added the code from the alpha instruction to make the HUD working in general, seem like there are some skills missing too.

**Comment by ortegamarcel** [comment]
Thanks for the info. I found the issue. I will release an hotfix soon, after doing some more testing. 

The problem is caused by an profession skill without a stat. When the settings are set, that it shows the basevalue behind profession skills, it breaks, since that skill doesn't have a stat. That setting is on by default. 

To get rid of it, until a hotfix is released, you can go to `Game Setting` -> `Configure Settings`-> `Token Action HUD TheWitcherTRPG` -> **Under `Skill Suffix` select `Skillpoints` or select `No` under `Show Skill Suffix`**
