### ISSUE TITLE
Not all skills are displayed

### ISSUE THREAD

**Issue by LinkDragmire** [ortegamarcel/fvtt-token-action-hud-thewitchertrpg#22]
there are skills missing in the hud. e.g. cast spell, the tab for will is active and selected and shows some of the other skills.. maybe it's a localization problem. I'm using the german version.

**Comment by ortegamarcel** [comment]
I have consciously decided not to display all skills in order to avoid overcrowding. Therefore, only the skills that I believe are most important will be displayed. However, this is of course very subjective.

Anyway, it is already planned for the next version that players (and the GM) can configure which skills are displayed and which are not.

If you don't want to wait for the next version, there is already a way to show/hide skills:

1. Open the following file with any text editor: `<foundry_root_folger>\modules\fvtt-token-action-hud-thewitchertrpg\scripts\constants.js`
2. The configuration starts from line 69: `export const SKILL = {`
3. All skills are listed underneath. It looks like this: `awareness: { stat: 'int', active: true, name: 'WITCHER.SkIntAwareness', statNum: 0, skillNum: 0 },`

**Comment by LinkDragmire** [comment]
Ok, valid option. Configuring all the way, sounds like a good idea, I will test to set some other skills to display.
