### ISSUE TITLE
Compatibility with my fork

### ISSUE THREAD

**Issue by Stexinator** [ortegamarcel/fvtt-token-action-hud-thewitchertrpg#49]
Hey,

I would like to discuss how/if we can manage compatibility with my fork. 

You can add me at discord with ``stexinator`` if you want to discuss it.

Greetings

**Comment by ortegamarcel** [comment]
I sent you an discord invite ('ein_toastbrot').

I actually planned to make it compatible with your fork, since I don't have much time to work on my own fork. Also the original isn't really active and it makes more sense to bundle our work together into one project, instead of everyone doing his own thing.

**Comment by AlexanderTheGr3at** [comment]
So for issues for this so I add it here or our you two working on moving this into the system? Because the weapon functions are working again but now none of the defence ones are lol.
